[project]
name = 'info.gianlucacosta.iris'

version = '0.0.0'

description = 'General-purpose library for Python'

readme = 'README.md'

authors = [{ name = "Gianluca Costa", email = "gianluca@gianlucacosta.info" }]

requires-python = ">=3.12"

dependencies = ["pytest==6.0", "black==22.1.0"]

keywords = [
  'library',
  'IoC container',
  'dependency injector',
  'versioning',
  'Maven',
  'rendering',
  'utilities',
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Topic :: Utilities",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pdm.scripts]
check-format = 'black src --diff --color'
verify = 'pytest tests'
