[project]
name = 'info.gianlucacosta.iris'

version = '0.0.0'

description = 'General-purpose library for Python'

authors = [{ name = "Gianluca Costa", email = "gianluca@gianlucacosta.info" }]

keywords = [
  'library',
  'IoC container',
  'dependency injector',
  'versioning',
  'Maven',
  'rendering',
  'utilities',
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Topic :: Utilities",
]

dependencies = ["pytest==9.1.1", "black==26.5.1"]
requires-python = "==3.12.*"
readme = 'README.md'
license = { text = "MIT" }

[tool.pdm.scripts]
check-format = 'black src --diff --color'
test = 'pytest tests'
verify = { composite = ['check-format', 'test'] }
