name: Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/verify-python-package@v11
        with:
          pdm-version: 2.28.1

      - uses: giancosta86/aurora-github/actions/publish-python-package@v11
        with:
          pdm-version: 2.28.0

          index-url: https://repo.repsy.io/giancosta86/pyground

          index-user: __token__

          index-secret: ${{ secrets.FAKE_PYTHON_TOKEN }}
